swagger: '2.0'

info:
  title: Option Pricing and Sensitivities
  description: Option pricing using advanced models such as Heston, Extended Merton, and Extended CGMY.
  version: 2.0.0

host: ${EXTERNAL_HOST} 
basePath: "/${VERSION_MAJOR}"
schemes:
  - https
produces:
  - application/json
  
paths: 
  $ref: spec.yml