name: benchmark pull requests
on: [pull_request]
jobs:
  runBenchmark:
    name: run benchmark
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly
    - uses: boa-dev/criterion-compare-action@v2.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}