name: release
on:
  push:
    tags:
    - '*'
env:
  CLOUDSDK_CORE_DISABLE_PROMPTS: 1
  PROJECT_ID: finside #use this as source of truth instead of terraform.tfvars
  CUSTOM_DOMAIN: api2.finside.org
  GCP_VERSION: v2
  RAPID_API_VERSION: v3
  SERVICE_NAME: realoptions2
  SERVICE_AUTH_NAME: realoptions2-auth

jobs:
  release: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: nightly

    - name: Build
      run: cargo build
    - name: Run tests nightly
      run: |
        cargo test

    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS}}
        export_default_credentials: true
        project_id: ${{ env.PROJECT_ID }}
    # Build and push image to Google Container Registry
    # see https://cloud.google.com/container-registry/docs/advanced-authentication#json-key
    - name: Build
      run: |
        cat ${GOOGLE_APPLICATION_CREDENTIALS} | docker login -u _json_key --password-stdin https://gcr.io
        docker build . -f docker/option_price.Dockerfile --tag gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA
        docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA

        docker build . -f docker/option_price_auth.Dockerfile --tag gcr.io/$PROJECT_ID/$SERVICE_AUTH_NAME:$GITHUB_SHA
        docker push gcr.io/$PROJECT_ID/$SERVICE_AUTH_NAME:$GITHUB_SHA

    - name: terraform 
      run: |
        cd terraform
        terraform init
        TF_LOG=debug terraform apply -auto-approve -var="custom_api_domain=$CUSTOM_DOMAIN" -var="gcp_api_version=$GCP_VERSION" -var="rapid_api_version=$RAPID_API_VERSION" -var="project=$PROJECT_ID" -var="github_sha=$GITHUB_SHA" -var="service_name=$SERVICE_NAME" -var="service_name_auth=$SERVICE_AUTH_NAME"
        cd ..
    - name: templatize yml
      run: |
        cd terraform
        VISIBLE_HOST=$CUSTOM_DOMAIN VERSION_MAJOR=$GCP_VERSION HOST=$(terraform output realoptions_gateway_url) source /dev/stdin <<<"$(echo 'cat <<EOF >final.yml'; cat ../docs/openapi_gcp.yml; echo EOF;)"
        mv -f final.yml ../docs/openapi_gcp.yml
        cat ../docs/openapi_gcp.yml
        cd ..

        VISIBLE_HOST=$CUSTOM_DOMAIN VERSION_MAJOR=$RAPID_API_VERSION source /dev/stdin <<<"$(echo 'cat <<EOF >final.yml'; cat ../docs/openapi_rapidapi.yml; echo EOF;)"
        mv -f final.yml ../docs/openapi_rapidapi.yml

    - name: release files
      uses: ncipollo/release-action@v1
      with:
        artifacts: "./target/x86_64-unknown-linux-musl/release/*,./serverless.yml,./docs/openapi_gcp.yml,./docs/openapi_rapidapi.yml"
        token: ${{ secrets.ACCESS_TOKEN }}
    - name: provision rapid api
      run: |
        curl --request POST 
        --url https://openapi-provisioning.p.rapidapi.com/v1/apis 
        --header 'content-type: multipart/form-data' 
        --header 'x-rapidapi-host: openapi-provisioning.p.rapidapi.com' 
        --header 'x-rapidapi-key: ${{ secrets.RAPID_API_TOKEN }}' 
        --form 'file=@docs/openapi_rapidapi.yml'

    - name: kickoff main site job
      run: |
        curl -s -X POST \
          -H "Content-Type: application/json" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token  ${{ secrets.ACCESS_TOKEN }}" \
          -d '{"event_type": "on-demand-test"}' \
          https://api.github.com/repos/realoptions/developer_site/dispatches

    
