name: test
on: [push]

jobs:
    test:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          rust: [nightly]

      steps:
      - uses: actions/checkout@v2
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}

      - name: Build
        run: cargo build

      - name: Run tests nightly with coverage
        env:
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: -Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort
          RUSTDOCFLAGS: -Cpanic=abort
          CRATE_NAME: utils
        run: |
          cargo build --verbose $CARGO_OPTIONS
          cargo test --verbose $CARGO_OPTIONS
          curl -L https://github.com/mozilla/grcov/releases/download/v0.5.15/grcov-linux-x86_64.tar.bz2 | tar jxf -
          zip -0 ccov.zip `find . \( -name "${CRATE_NAME}*.gc*" \) -print`
          ./grcov ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore "/*" -o lcov.info
          bash <(curl -s https://codecov.io/bash) -f lcov.info -t ${{ secrets.CODECOV_TOKEN }}
    integrations:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: hecrj/setup-rust-action@v1
          with:
            rust-version: nightly
        - name: Build
          run: cargo build --release
        - name: Run integration tests
          run: |
            npm ci
            npm test -- --runInBand
          env:
            CI: true
